services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "5175:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo

volumes:
  mongo-data:
